CREATE TABLE mahasiswa(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NIM            CHAR(8)      NOT NULL,
   NAMA           VARCHAR(20)  NOT NULL,
   ADDRESS        VARCHAR(50)  NOT NULL,
   JURUSAN        VARCHAR(30)  NOT NULL
);

CREATE TABLE jurusan(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   JURUSAN    VARCHAR(30)  NOT NULL
);

CREATE TABLE dosen(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAMA       VARCHAR(20)  NOT NULL
);

CREATE TABLE matakuliah(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAMA       VARCHAR(20)  NOT NULL,
   SKS        VARCHAR(30)  NOT NULL
);

INSERT INTO mahasiswa(NIM,NAMA,ADDRESS,JURUSAN)
VALUES ( '10115110', 'Adnan Radja Maulana', 'Ujungberung', 'MATEMATIKA' );

INSERT INTO jurusan(JURUSAN)
VALUES ('MATEMATIKA');

INSERT INTO dosen(NAMA)
VALUES ('Warsoma');

INSERT INTO matakuliah(NAMA,SKS)
VALUES ('MATEMATIKA', '4');
